spring.application.name=olx-saas

# Render Port (Cloud ke liye zaroori hai)
server.port=${PORT:8080}

# Smart Database Logic
# Agar Cloud hai to waha ka URL use karega, nahi to Local MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/olx_saas_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:as761039}

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true